INSERT INTO `creature_names`
  (entry, name, subname, info_str, Flags1, type, family, rank, unk4, spelldataid, male_displayid, female_displayid, male_displayid2, female_displayid2, unknown_float1, unknown_float2, civilian, leader)
VALUES
  (38000, "Arthas Menethil", "Ruler of the Scourge", "", 0, 6, 0, 1, 0, 0, 10729, 0, 0, 0, 18, 5, 0, 0);

INSERT INTO `creature_proto`
  (entry, minlevel, maxlevel, faction, minhealth, maxhealth, mana, scale, npcflags, attacktime, attacktype, mindamage, maxdamage, rangedattacktime, rangedmindamage, rangedmaxdamage, mountdisplayid, equipmodel1, equipinfo1, equipslot1, equipmodel2, equipinfo2, equipslot2, equipmodel3, equipinfo3, equipslot3, respawntime, armor, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, combat_reach, bounding_radius, auras, boss, money, invisibility_type, death_state, walk_speed, run_speed, fly_speed, extra_a9_flags)
VALUES
  (38000, 81, 86, 21, 2246497, 2346497, 12840, 1, 0, 2000, 0, 12240, 12882, 0, 0, 0, 0, 7489, 33490946, 273, 0, 0, 0, 0, 0, 0, 0, 4410, 0, 0, 0, 0, 0, 0, 2.25, 1, "17467", 1, 682, 0, 0, 2.5, 8, 14, 0);

INSERT INTO `creature_names`
  (entry, name, subname, info_str, Flags1, type, family, rank, unk4, spelldataid, male_displayid, female_displayid, male_displayid2, female_displayid2, unknown_float1, unknown_float2, civilian, leader)
VALUES
  (38001, "Ghost of Muradin", "", "", 5242886, 8, 8, 0, 0, 0, 10045, 0, 0, 0, 1, 1, 1, 0);

INSERT INTO `creature_names`
  (entry, name, subname, info_str, Flags1, type, family, rank, unk4, spelldataid, male_displayid, female_displayid, male_displayid2, female_displayid2, unknown_float1, unknown_float2, civilian, leader)
VALUES
  (38002, "Ghost of Arthas", "", "", 5242886, 8, 8, 0, 0, 0, 10045, 0, 0, 0, 1, 1, 1, 0);

INSERT INTO `creature_proto`
  (entry, minlevel, maxlevel, faction, minhealth, maxhealth, mana, scale, npcflags, attacktime, attacktype, mindamage, maxdamage, rangedattacktime, rangedmindamage, rangedmaxdamage, mountdisplayid, equipmodel1, equipinfo1, equipslot1, equipmodel2, equipinfo2, equipslot2, equipmodel3, equipinfo3, equipslot3, respawntime, armor, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, combat_reach, bounding_radius, auras, boss, money, invisibility_type, death_state, walk_speed, run_speed, fly_speed, extra_a9_flags)
VALUES
  (38001, 1, 1, 35, 64, 64, 0, 1, 0, 2000, 0, 163, 218, 0, 0, 0, 0, 33304, 33490690, 789, 33307, 33490436, 1038, 0, 0, 0, 360000, 20, 0, 0, 0, 0, 0, 0, 1, 1, "0", 0, 0, 0, 0, 2.5, 8, 14, 0);

INSERT INTO `creature_proto`
  (entry, minlevel, maxlevel, faction, minhealth, maxhealth, mana, scale, npcflags, attacktime, attacktype, mindamage, maxdamage, rangedattacktime, rangedmindamage, rangedmaxdamage, mountdisplayid, equipmodel1, equipinfo1, equipslot1, equipmodel2, equipinfo2, equipslot2, equipmodel3, equipinfo3, equipslot3, respawntime, armor, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, combat_reach, bounding_radius, auras, boss, money, invisibility_type, death_state, walk_speed, run_speed, fly_speed, extra_a9_flags)
VALUES
  (38002, 1, 1, 35, 64, 64, 0, 1, 0, 2000, 0, 163, 218, 0, 0, 0, 0, 33304, 33490690, 789, 33307, 33490436, 1038, 0, 0, 0, 360000, 20, 0, 0, 0, 0, 0, 0, 1, 1, "0", 0, 0, 0, 0, 2.5, 8, 14, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84905, 23584, 568, 28.7776, 1464.02, 1.29598, 4.96548, 0, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84906, 1412, 568, 45.4748, 1422.08, 1.44717, 3.68438, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84907, 23581, 568, 102.864, 1421.43, -0.461175, 3.02404, 0, 22276, 1890, 72, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84908, 24179, 568, 102.814, 1418.42, -1.54918, 3.02403, 12, 22262, 1890, 8, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84909, 1412, 568, 67.6886, 1383.24, -2.96227, 1.8675, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84910, 23582, 568, 19.0948, 1420.57, 12.073, 5.8294, 12, 22272, 1890, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84911, 24396, 568, 97.4068, 1374.91, -20.3624, 3.28122, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84912, 1412, 568, 162.754, 1396.37, 6.28446, 0.488692, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84913, 1412, 568, 42.0208, 1364.56, 9.15192, 0.174533, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84914, 24396, 568, 90.4027, 1365.51, -23.7238, 5.67232, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84915, 24396, 568, 130.454, 1360.01, -23.8173, 5.27089, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84916, 24396, 568, 83.4719, 1352.88, -24.6725, 5.41052, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84917, 24396, 568, 137.737, 1372.67, -21.7763, 3.80482, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84918, 24396, 568, 179.96, 1235.51, -17.2034, 0.174533, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84919, 24396, 568, 167, 1241.68, -20.6369, 3.45575, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84920, 1412, 568, 184.472, 1178.79, 2.19037, 4.94136, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84921, 24396, 568, 73.1334, 1228.39, -17.6483, 4.04916, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84922, 24396, 568, 92.9063, 1218.39, -17.8938, 3.97935, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84923, 24396, 568, 84.323, 1224.2, -21.9573, 4.57276, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84924, 23584, 568, -22.7246, 1490.84, 16.2231, 0.704053, 0, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84925, 23584, 568, -51.2534, 1478.33, 15.8948, 5.99843, 0, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84926, 23576, 568, 16.9616, 1414.6, 12.0265, 6.23083, 0, 21631, 1890, 108, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84927, 14881, 568, 88.5021, 1723.07, 42.1215, 2.24801, 12, 9829, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84928, 14881, 568, 104.291, 1665.23, 42.1216, 3.19282, 12, 1160, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84929, 14881, 568, 162.911, 1700.49, 42.1216, 2.24459, 0, 14952, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84930, 23574, 568, 376.353, 1407.34, 75.6313, 3.45575, 0, 21630, 1890, 76, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84931, 23578, 568, -18.6421, 1150.46, 18.8947, 3.19395, 0, 21633, 1890, 76, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84932, 23577, 568, 370.257, 1135.74, 6.64913, 4.76475, 0, 21632, 1890, 76, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84933, 1412, 568, 157.956, 1405.28, 4.5494, 1.1807, 0, 134, 31, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84934, 24396, 568, 114.507, 1206.05, -20.2204, 5.07555, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84935, 24396, 568, 136.384, 1206.17, -12.7505, 5.03438, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84936, 24530, 568, 187.077, 1172.54, 0.949389, 4.38078, 0, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84937, 24064, 568, 162.531, 1135.59, 0.68252, 1.13446, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84938, 24530, 568, 148.932, 1113.78, 1.40726, 0.122173, 0, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84939, 24064, 568, 148.186, 1125.2, 2.23474, 3.19395, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84940, 24064, 568, 169.462, 1130.48, 1.19779, 5.51524, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84941, 24064, 568, 155.335, 1130.25, 1.27472, 0.907571, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84942, 23596, 568, -78.7532, 1150.4, 5.59613, 3.07178, 12, 22307, 1890, 8, 512, 4096, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84943, 24065, 568, 226.748, 1069.44, 0.225, 0.253145, 0, 22303, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84944, 24065, 568, 237.798, 1078.2, 0.225, 5.75236, 0, 22304, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84945, 24065, 568, 236.597, 1115.74, 0.183333, 1.67552, 0, 22304, 1890, 8, 16777472, 4097, 13, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84946, 24064, 568, 237.411, 1135.67, 0.183334, 5.86431, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84947, 24064, 568, 228.512, 1126.03, 0.183332, 4.01426, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84948, 24064, 568, 245.382, 1138.24, 0.183332, 5.16617, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84949, 23597, 568, 252.705, 1026.29, 16.5259, 2.40765, 12, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84950, 24047, 568, 285.878, 1033.32, -3.4494, 0.716387, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84952, 14881, 568, 70.3411, 1682.57, 42.1215, 1.47469, 0, 14952, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84953, 14881, 568, 99.506, 1656.89, 42.1216, 5.431, 0, 9829, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84954, 23584, 568, 19.7148, 1477.93, 2.87978, 1.162, 12, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84955, 24396, 568, 87.9165, 1377.64, -18.9555, 0.0536751, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84956, 24065, 568, 179.6, 1139.08, 0.225, 4.69055, 0, 22304, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84957, 23597, 568, 249.004, 1043.29, 3.67493, 1.79769, 0, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84958, 23597, 568, 234.088, 1039.92, 3.65883, 2.11185, 0, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84959, 23596, 568, 243.45, 1033.66, 3.65167, 1.8675, 0, 22308, 1890, 8, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84960, 23897, 568, 250.141, 996.782, 11.0915, 2.00713, 0, 21893, 35, 0, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84961, 24064, 568, 230.744, 1066.13, 0.313122, 3.87463, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84962, 24064, 568, 242.575, 1075.25, 0.475, 2.54818, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84963, 24064, 568, 248.592, 1084.99, 0.225, 0.785398, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84964, 24064, 568, 236.318, 1088.26, 0.225, 2.16421, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84965, 24064, 568, 226.897, 1079.17, 0.225, 3.82227, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84966, 24065, 568, 361.707, 1117.68, 6.58402, 4.69494, 0, 22304, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84967, 14881, 568, 102.092, 1665.99, 42.1216, 4.17111, 0, 2536, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84968, 24396, 568, 146.228, 1230.19, -24.0164, 0.864965, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84969, 24059, 568, 114.078, 1181.71, -14.9536, 1.49065, 0, 22301, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84970, 23596, 568, 110.845, 1178.93, -9.22066, 1.48996, 12, 22308, 1890, 8, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84971, 24064, 568, 174.279, 1169.49, 1.02423, 2.10898, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84972, 24064, 568, 186.895, 1162.7, 0.225, 3.69895, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84973, 24065, 568, 177.831, 1125.88, 0.225, 1.80634, 0, 22303, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84974, 24064, 568, 174.874, 1122.57, 0.376435, 1.90075, 12, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84975, 24065, 568, 233.329, 1135.77, 0.225, 3.20612, 0, 22303, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84976, 23597, 568, 245.998, 1025.58, 3.56834, 3.37199, 12, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84977, 24138, 568, 293.242, 1052.87, 0.145983, 2.73278, 12, 1038, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84978, 24059, 568, 286.358, 1050.58, 0.145983, 2.87853, 12, 22301, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84979, 24047, 568, 298.019, 1023.41, -1.29662, 3.03956, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84980, 23597, 568, 338.112, 1051.79, 9.70488, 5.25344, 0, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84981, 23597, 568, 347.843, 1126.1, 6.64986, 0.239687, 12, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84982, 24047, 568, 302.611, 1004.57, -5.45138, 5.89643, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84983, 24530, 568, 364.396, 1048.9, 9.68343, 4.76475, 0, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84984, 23597, 568, 346.195, 1046.09, 9.69506, 3.14159, 0, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84985, 23597, 568, 337.235, 1022.44, 9.70534, 4.5204, 0, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84986, 23597, 568, 327.933, 1030.54, 9.70501, 3.29867, 0, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84987, 23597, 568, 358.713, 1112.35, 5.97011, 0.733038, 0, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84988, 23596, 568, 364.306, 1112.51, 5.86931, 2.46091, 0, 22308, 1890, 8, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84989, 23597, 568, 356.791, 1124.74, 6.76001, 6.23803, 0, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84990, 23596, 568, 376.49, 1112.34, 6.15811, 1.01229, 12, 22307, 1890, 8, 512, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84991, 24065, 568, 367.733, 1042.91, 9.68983, 0.0349066, 12, 22304, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84992, 24047, 568, 316.187, 986.007, -5.43503, 3.51373, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84993, 24065, 568, 372.493, 1044.07, 9.68696, 3.57792, 12, 22303, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84994, 24530, 568, 375.055, 1050.34, 9.68932, 4.60767, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84995, 24047, 568, 331.192, 980.918, -3.03844, 2.48911, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84996, 24059, 568, 377.429, 1004.25, 0.225, 1.16855, 12, 22302, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84997, 24047, 568, 338.189, 958.194, -2.68485, 2.05469, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84998, 23597, 568, 397.708, 1048.77, 9.7045, 6.10865, 12, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (84999, 24059, 568, 375.964, 997.862, 0.225, 2.21345, 12, 22301, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85000, 23597, 568, 400.797, 1022.44, 9.70558, 4.66003, 12, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85001, 24047, 568, 353.326, 922.022, -3.32803, 3.77354, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85002, 23597, 568, 411.553, 1022.26, 9.70508, 4.7822, 12, 22310, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85003, 23597, 568, 406.069, 1044.39, 9.70488, 2.35619, 12, 22309, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85004, 24065, 568, 406.433, 1054.87, 9.70489, 4.5204, 12, 22303, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85005, 24059, 568, 414.678, 992.372, 0.225, 6.28029, 12, 22302, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85006, 24047, 568, 361.174, 899.834, -2.53661, 1.56519, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85007, 24059, 568, 430.512, 987.603, 0.225, 5.46876, 12, 22302, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85008, 24047, 568, 365.858, 877.02, -2.62539, 4.56402, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85009, 24047, 568, 280.986, 899.747, 0.736498, 4.5392, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85010, 24047, 568, 289.347, 873.808, -1.5135, 5.97608, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85011, 24047, 568, 280.653, 889.301, -0.263502, 4.3949, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85012, 24047, 568, 275.493, 876.707, -1.0135, 0.694507, 0, 834, 190, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85013, 24043, 568, 428.445, 898.907, 0.225, 3.72616, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85014, 24043, 568, 415.068, 881.682, 0.314489, 3.207, 0, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85015, 24043, 568, 424.37, 874.396, 0.925673, 2.87577, 0, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85016, 24043, 568, 402, 876.37, 0.332886, 1.78941, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85017, 24043, 568, 452.703, 951.752, 0.35, 4.56629, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85018, 24043, 568, 457.184, 936.734, 0.677344, 3.72968, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85019, 24043, 568, 441.122, 955.089, 0.24238, 4.91989, 12, 19705, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85020, 24175, 568, 206.921, 1473.42, 26.1001, 3.9619, 0, 22161, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85021, 24180, 568, 223.8, 1424.94, 29.5698, 1.16937, 0, 22264, 1890, 8, 16777472, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85022, 24179, 568, 232.749, 1428.7, 28.9242, 1.8326, 0, 22261, 1890, 8, 512, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85023, 24180, 568, 224.069, 1394.26, 40.2985, 1.309, 0, 22263, 1890, 8, 16777472, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85024, 24179, 568, 231.797, 1393.42, 40.6887, 1.69297, 0, 22261, 1890, 8, 512, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85025, 24396, 568, 145.958, 1367.13, -23.4551, 5.01159, 0, 6295, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85026, 24180, 568, 244.807, 1367.66, 49.0498, 2.61799, 0, 22263, 1890, 8, 16777472, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85027, 24179, 568, 246.908, 1375.15, 49.505, 2.89725, 0, 22262, 1890, 8, 512, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85028, 24180, 568, 274.358, 1385.16, 49.505, 3.75246, 0, 22263, 1890, 8, 16777472, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85029, 24179, 568, 284.044, 1372.32, 49.505, 2.77507, 0, 22262, 1890, 8, 512, 4097, 375, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85030, 24549, 568, 301.122, 1385.6, 57.8531, 3.26377, 0, 22538, 1890, 8, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85031, 14881, 568, 174.359, 1652.93, 42.1216, 1.69484, 0, 14952, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85032, 24396, 568, 146.133, 1353.18, -24.7096, 5.76695, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85033, 24064, 568, 176.759, 1174.59, 0.149227, 5.4113, 0, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85034, 24064, 568, 175.727, 1144.93, 0.225, 4.69048, 12, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85035, 23582, 568, 14.5413, 1411.64, 12.0486, 0.0174533, 0, 22272, 1890, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85036, 23584, 568, -11.6385, 1479.31, 9.47306, 3.73788, 0, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85037, 23584, 568, -54.2842, 1487.61, 18.4586, 1.88581, 12, 22467, 44, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85038, 14881, 568, 85.0794, 1725.62, 42.1215, 2.37204, 0, 14952, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85039, 14881, 568, 172.819, 1730.79, 42.1216, 0.815531, 0, 9829, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85040, 23582, 568, 86.4654, 1458.96, 13.0063, 1.44773, 12, 22272, 1890, 72, 16777472, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85041, 24064, 568, 196.915, 1171.77, 1.39923, 5.20384, 12, 22517, 16, 1, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85042, 24396, 568, 164.018, 1231.78, -18.1414, 5.85817, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85043, 24396, 568, 146.635, 1219.42, -18.7664, 6.27474, 0, 901, 188, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `creature_spawns`
  (id, entry, map, position_x, position_y, position_z, orientation, movetype, displayid, faction, flags, bytes, bytes2, emote_state, npc_respawn_link, channel_spell, channel_target_sqlid, channel_target_sqlid_creature, standstate)
VALUES
  (85044, 14881, 568, 78.7873, 1690.95, 42.1215, 0.527023, 0, 14952, 190, 0, 16908544, 4097, 0, 0, 0, 0, 0, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30204, 186305, 568, 124.203, 1022.95, 34.1441, -1.57952, 0, 0, -0.710185, 0.704015, 1, 32, 1375, 0.935587, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30205, 187036, 568, 98.8152, 1245.41, -9.49482, 1.43117, 0, 0, 0.656059, 0.75471, 1, 32, 1375, 2.7, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30206, 187037, 568, 132.373, 1244.41, -9.6476, 0.296706, 0, 0, 0.147809, 0.989016, 1, 32, 1375, 2.7, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30207, 186860, 568, 99.9827, 1333.95, -9.39569, 0.593412, 0, 0, 0.292372, 0.956305, 1, 32, 1375, 2.7, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30208, 187035, 568, 132.464, 1334.19, -9.37467, -2.53073, 0, 0, 0.953717, -0.300706, 1, 32, 1375, 2.7, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30209, 186858, 568, 337.066, 1396.09, 74.1723, -2.85361, 0, 0, 0.989651, -0.143493, 0, 32, 114, 1.14368, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30210, 186303, 568, 305.908, 1112.09, 9.9566, 3.14159, 0, 0, 1, -4.37114E-8, 1, 32, 1375, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30211, 186728, 568, 120.294, 1605.67, 63.1804, 3.1402, 0, 0, 1, 0.000696019, 0, 32, 114, 0.972855, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30212, 186304, 568, 375.41, 1057.67, 9.86144, -1.5708, 0, 0, -0.707107, 0.707107, 0, 32, 1375, 1.06644, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30213, 186306, 568, 123.256, 914.422, 34.1441, -1.57952, 0, 0, -0.710185, 0.704015, 1, 34, 0, 0.935587, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30214, 186859, 568, 120.294, 732.009, 45.011, 1.56207, 0, 0, 0.704015, 0.710186, 0, 32, 1375, 1.2, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30215, 186482, 568, -22.0915, 1350.19, 48.1739, 2.26893, 0, 0, 0.906308, 0.422618, 1, 0, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30216, 186338, 568, -23.4402, 1333.18, 48.1739, 0.0174533, 0, 0, 0.00872654, 0.999962, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30217, 185455, 568, -24.0499, 1343.66, 48.1739, -0.0698131, 0, 0, 0.0348995, -0.999391, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30218, 185454, 568, -28.1068, 1338.44, 48.1739, -1.53589, 0, 0, 0.694658, -0.71934, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30219, 187379, 568, -73.7866, 1164.58, 5.2034, 3.14159, 0, 0, 1, -4.37114E-8, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30220, 186482, 568, -74.6319, 1138.7, 5.20206, 0, 0, 0, 0, 1, 1, 0, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30221, 185434, 568, -73.5284, 1139.15, 5.19407, -2.26893, 0, 0, 0.906308, -0.422618, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30222, 186430, 568, 251.429, 996.856, 10.912, 2.11185, 0, 0, 0.870356, 0.492424, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30223, 187380, 568, 383.674, 1083.18, 5.75323, 0.0174533, 0, 0, 0.00872654, 0.999962, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30224, 185455, 568, 298.285, 1454.72, 81.5059, 0.244346, 0, 0, 0.121869, 0.992546, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30225, 186482, 568, 294.252, 1457.96, 81.5059, -1.3439, 0, 0, 0.622515, -0.782608, 1, 0, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30226, 185454, 568, 297.778, 1461.44, 81.5059, -1.8675, 0, 0, 0.803857, -0.594823, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30227, 185455, 568, 291.797, 1464.71, 81.506, 0.680678, 0, 0, 0.333807, 0.942641, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30228, 187378, 568, 296.334, 1468.37, 81.506, -2.51327, 0, 0, 0.951057, -0.309017, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30229, 185455, 568, 300.462, 1470.83, 81.506, 1.88496, 0, 0, 0.809017, 0.587785, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30230, 185454, 568, 305.403, 1460.19, 81.5059, -1.18682, 0, 0, 0.559193, -0.829037, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30231, 185454, 568, 337.444, 1323.92, 81.5876, -2.89725, 0, 0, 0.992546, -0.121869, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30232, 185455, 568, 335.697, 1314.94, 81.5876, 0.314159, 0, 0, 0.156434, 0.987688, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30233, 186482, 568, 341.059, 1311.29, 81.5876, 0.0174533, 0, 0, 0.00872654, 0.999962, 1, 0, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30234, 185455, 568, 341.998, 1320.82, 81.5876, -0.907571, 0, 0, 0.438371, -0.898794, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30235, 185454, 568, 346.202, 1314.28, 81.5876, 1.95477, 0, 0, 0.829038, 0.559193, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30236, 185434, 568, 343.361, 1311.33, 81.5876, 0.0174533, 0, 0, 0.00872654, 0.999962, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30237, 185454, 568, 345.458, 1324.55, 81.5876, 0.837758, 0, 0, 0.406737, 0.913545, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30238, 186482, 568, 383.488, 1152.29, 6.34366, 3.12414, 0, 0, 0.999962, 0.00872656, 1, 0, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30239, 185438, 568, 398.786, 1086.32, 5.35751, 2.84489, 0, 0, 0.989016, 0.147809, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30240, 185434, 568, 392.563, 1155.37, 6.34364, -1.81514, 0, 0, 0.788011, -0.615661, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30241, 186338, 568, 397.309, 1083.46, 5.41724, -0.0174535, 0, 0, 0.00872664, -0.999962, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30242, 186338, 568, 398.437, 1152.45, 6.34364, 3.14159, 0, 0, 1, -4.37114E-8, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30243, 185454, 568, 396.143, 1148.68, 6.34339, 2.56563, 0, 0, 0.95882, 0.284015, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30244, 185454, 568, 411.937, 1123.93, 6.10051, -0.436333, 0, 0, 0.21644, -0.976296, 1, 0, 0, 1, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30245, 186338, 568, 417.834, 1499.6, 81.6332, 2.28638, 0, 0, 0.909961, 0.414693, 1, 2, 14, 1.5, 0);

INSERT INTO `gameobject_spawns`
  (id, Entry, map, position_x, position_y, position_z, Facing, orientation1, orientation2, orientation3, orientation4, State, Flags, Faction, Scale, stateNpcLink)
VALUES
  (30246, 186338, 568, 407.256, 1502.67, 81.6372, -1.65806, 0, 0, 0.737277, -0.67559, 1, 2, 14, 1.5, 0);
